### ISSUE TITLE
Unable to create new container

### ISSUE THREAD

**Issue by mspieth376** [sterfield/openvz-module#1]
Using the following:
- openvz:
  veid: 601
  state: present
  ostemplate:
  - debian-7.0-base_2.tar.gz

I get the following responce from ansible:

vps-download ERROR: template [udebian-7.0-base_2.tar.gz] not found!
Cached OS template /vz/template/cache/[udebian-7.0-base_2.tar.gz].tar[.gz|.bz2|.xz] not found
Creation of container private area failed

I also noticed that when setting the hostname to something such as host.host.com the actual hostname gets set to [uhost.host.com

I'm not sure where its getting the [u from

**Comment by sterfield** [comment]
Hi,

I don't know where the '[u' come from but it seems that there's two place where it's being displayed:
- the ostemplate
- and the hostname

Can you please precise me:
- the python version on the hypervisor involved ?
- the os ran on the hypervisor
- the kernel
- the ansible version

I'll then try to find the issue.

Thanks,

**Comment by mspieth376** [comment]
(Ansible Server)
python --version
Python 2.7.3

ansible --version
ansible 1.6.6

(Remote Node)
OS: debian 7
uname -r
2.6.32-openvz-042stab108.8-amd64

python --version
Python 2.7.3

**Comment by sterfield** [comment]
Your ansible version is very old. I don't know if it's the issue, but we could try.

Can you please make a python virtualenv, install ansible from pip repository and retry ?

**Comment by mspieth376** [comment]
I had already contemplated that my ansible version could possibly be the problem. I am in the process of cloning the instance to test the upgrade now. Its 76gigs to It will take a while. I'll check it again tomorrow.

Thanks for you help!

**Comment by sterfield** [comment]
OK, please let me know.

Thanks !

**Comment by mspieth376** [comment]
I upgraded to:
ansible 1.9.3
  configured module search path = /usr/share/ansible/

the u disappeared however I still get the same basic error:

Command invoked : vzctl create 601 --layout simfs  --ostemplate ['debian-7.0-base_2.tar.gz']
Stderr : 
vps-download WARNING: no public gpg key security@openvz.org found,
disabling signature check. To import the public key, see
http://wiki.openvz.org/Package_signatures#Importing_the_public_key

vps-download ERROR: template [debian-7.0-base_2.tar.gz] not found!
Cached OS template /vz/template/cache/[debian-7.0-base_2.tar.gz].tar[.gz|.bz2|.xz] not found
Creation of container private area failed

FATAL: all hosts have already failed -- aborting

**Comment by mspieth376** [comment]
I found the issue its was a formatting problem with my definition in my tasks file.
